### ISSUE TITLE
How to get resource ids?

### ISSUE THREAD

**Issue by gaelg** [juangabreil/php-sdmx#1]
First, thank you for this nice library :)

I'm willing to use $client->getTimeSeries() to get the data, but I can't find the right string to put in the $resource argument. Is there a way to get the list of available resource ids?

**Comment by juangabreil** [comment]
Hi gaelg,

You could do: getDataflowStructure with parameter full set to true. So you will get the structure of the dataflow will all the possible values for each data type. The resource string is just a series of values (separated by points) for each dimension (e.g. A+B.EU.1223 would be equivalent to where (DIM1 = A OR DIM1 = B) AND DIM2 = EU AND DIM3 = 1223)

Hope this will help you

**Comment by gaelg** [comment]
Yes, thank you, I figured it out in the meanwhile.
